# personalised the PS1
PS1='\[\033[1;32m\]\u\[\033[00m\][\[\033[1;34m\]\W\[\033[00m\]]$(__git_ps1 "(\[\033[1;31m\]%s\[\033[00m\])")\$ '

# defined alias
alias sf="./app/console"
alias phpspec="./bin/phpspec"
alias behat="./bin/behat"
alias tmux='tmux -2'
alias g="git"
alias phpi="php -a"
alias sfr="./app/console ro:de"
alias sfc="./app/console cont:de"
alias sfrg="./app/console ro:de | grep"
alias sfcg="./app/console cont:de | grep"
